export const REQUEST_REGIST = 'REQUEST_REGIST'
export const SUCCESS_REGIST = 'SUCCESS_REGIST'
export const FAILURE_REGIST = 'FAILURE_REGIST'

export const INPUT_NEWUSERNAME = 'INPUT_NEWUSERNAME'
export const INPUT_NEWPASSWORD = 'INPUT_NEWPASSWORD'
export const INPUT_CONFIRMPASSWORD = 'INPUT_CONFIRMPASSWORD'
export const RESET = 'RESET'

export const GO_TO_LOGIN = 'GO_TO_LOGIN'